### ISSUE TITLE
Allow hyperlinks in the DropCap content

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/drop-cap#1]
This is a clone from the original `spikes` repo.

I have gone through a sample
https://github.com/novoda/spikes/tree/master/drop-cap

Can you please let me know how can i give hyperlink to a specified text in dropcapview.

It would be helpful if you can respond ASAP.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
