### ISSUE TITLE
Could not find com.novoda:drop-cap:1.1.0.

### ISSUE THREAD

**Issue by lukicmarko** [novoda/drop-cap#2]
After updating to Android Studio 3.4
```
Could not find com.novoda:drop-cap:1.1.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.pom
  - https://repo.maven.apache.org/maven2/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.jar
  - https://jcenter.bintray.com/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.pom
  - https://jcenter.bintray.com/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.jar
  - https://maven.google.com/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.pom
  - https://maven.google.com/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.jar
  - https://dl.google.com/dl/android/maven2/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.pom
  - https://dl.google.com/dl/android/maven2/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.jar
  - https://maven.fabric.io/public/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.pom
  - https://maven.fabric.io/public/com/novoda/drop-cap/1.1.0/drop-cap-1.1.0.jar
Required by:
    project :app

```

**Comment by mr-archano** [comment]
Hi @lukicmarco, thanks for the headsup. This seems another side-effect of the migration of our Bintray account.
We will take a look and keep you posted, but in the meantime the fastest workaround could be to add the Bintray maven repo to your build like mentioned in https://github.com/novoda/espresso-support/issues/24

**Comment by lukicmarko** [comment]
@mr-archano thanks.

**Comment by mr-archano** [comment]
@lukicmarko it seems like the issue with JCenter has been resolved. This means that you should not be needing the additional buildscript repo mentioned above anymore, as the package is available in JCenter:
http://jcenter.bintray.com/com/novoda/drop-cap/
