### ISSUE TITLE
Span and Styles

### ISSUE THREAD

**Issue by rakotonirinaT** [novoda/drop-cap#6]
Thank you very much for your great efforts to make this project happen. I tried it to replace my normal TextView, but unfortunately failed due to the Spannable functions I use inside of it.
Is there no way please to make the DropCap view accepting Spans?

Regards,
Tsiry

**Comment by blundell** [comment]
@Mecharyry do you know? :-)

**Comment by MechaRyRy** [comment]
Ha, unfortunately this library doesn't support Spans. As far as I know, Spans only come with TextView and unfortunately we are not extending from `TextView`. In terms of supporting it, this would be a very large feature. I'm thinking of reworking `DropCap` to create a `custom view` that will support all of this. It will take sometime though unfortunately.

**Comment by phpSing** [comment]
Thank you very much for your great efforts to make this project happen. Searched all github & stackoverflow, there is a @times-components/article-paragraph lib but only support android, this is the only one for iOS out there, hope we can keep it up.

Thanks again

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
